// DO NOT MODIFY, this is generated by str-rom.js

#ifndef STRINGS_H
#define STRINGS_H

#include "util.h"

#define eol 1

enum string_names {
  blankStr,
  mainMenuStr,
  pasteStr,
  pickStr,
  inspectStr,
  settingsStr,
  menuHelpStr,
  helpMenuStr,
  hm1Str,
  hm2Str,
  hm3Str,
  hm4Str,
  hm5Str,
  helpMenu2Str,
  hm6Str,
  hm7Str,
  hm8Str,
  hm9Str,
  hm10Str,
  hm11Str,
  hm12Str,
  hm13Str,
  pasteScreenStr,
  paste1Str,
  paste2Str,
  lightsStr,
  focusStr,
  zoomStr,
  pickScreenStr,
  pick1Str,
  pick2Str,
  inspectScreenStr,
  inspect1Str,
  inspect2Str,
  inspect3Str,
  settingsMenuStr,
  sm1Str,
  sm2Str,
  sm3Str,
};

#define MAX_ROMSTR_SIZE 23

const uint16 strRomOfs[] = {
  0,
  1,
  6,
  10,
  17,
  22,
  27,
  38,
  43,
  53,
  62,
  71,
  80,
  91,
  99,
  109,
  119,
  128,
  136,
  146,
  155,
  159,
  164,
  170,
  180,
  190,
  197,
  204,
  210,
  218,
  223,
  232,
  240,
  245,
  249,
  258,
  265,
  272,
  276,
};

void initStringsRom();
char *romStr(uint8 strId);

#endif
