// DO NOT MODIFY, this is generated by str-rom.js

#ifndef STRINGS_H
#define STRINGS_H

#include "util.h"

#define eol 1

enum string_names {
  blankStr,
  mainMenuStr,
  pasteStr,
  pickStr,
  inspectStr,
  settingsStr,
  menuHelpStr,
};

#define MAX_ROMSTR_SIZE 23

const uint16 strRomOfs[] = {
  0,
  1,
  6,
  10,
  17,
  22,
  27,
};

void initStringsRom();
char *romStr(uint8 strId);

#endif
